# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

SuperAdmin.create(name: 'Krishnaprasad Varma', email: "kpvarma@yopmail.com", username: "kpvarma", password: "Password@1", password_confirmation: "Password@1")
SuperAdmin.create(name: 'K C Murali', email: "kcmurali@yopmail.com", username: "kcmurali", password: "Password@1", password_confirmation: "Password@1")

shiva_temple = Trust.create(name: 'Shiva temple Trust', status: 'active', email: "thiruvannur@yopmail.com", phone: "0495-2332332", address: "Thiruvannur Nada(PO)", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
tpkws = Trust.create(name: 'TPKWS', status: 'active', email: "tpkws@yopmail.com", phone: "0495-2341231", address: "Thiruvannur Nada(PO)", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
kovil = Trust.create(name: 'Murugan Kovil', status: 'active', email: "kovil@yopmail.com", phone: "0495-2312313", address: "Thiruvannur Nada(PO)", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
guruvayoor = Trust.create(name: 'Guruvayoor Devaswom', status: 'active', email: "guruvayoor@yopmail.com", phone: "0495-2421232", address: "Thiruvannur Nada(PO)", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
mammiyoor = Trust.create(name: 'Mammiyoor Devaswom', status: 'active', email: "mammiyoor@yopmail.com", phone: "0495-2421632", address: "Thiruvannur Nada(PO)", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
tali = Trust.create(name: 'Tali Devaswom', status: 'active', email: "tali@yopmail.com", phone: "0495-2428231", address: "Thiruvannur Nada(PO)", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
varakkal = Trust.create(name: 'Varakkal Devaswom', status: 'active', email: "varakkal@yopmail.com", phone: "0495-2426232", address: "Thiruvannur Nada(PO)", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

rajettan = Admin.create(name: 'Pritviraj', email: "rajettan@yopmail.com", username: "rajettan", status: 'active', address: "Puthiya Kovilakam, Thiruvannur Nada (PO)", password: "Password@1", password_confirmation: "Password@1", trust: shiva_temple)
jitheshettan = Admin.create(name: 'Jithesh Raja', email: "jitheshettan@yopmail.com", username: "jitheshettan", address: "Jithesh Nivas, Thiruvannur Nada (PO)", status: 'active', password: "Password@1", password_confirmation: "Password@1", trust: shiva_temple)
tpkws = Admin.create(name: 'Mohana Varma', email: "mohanavarma@yopmail.com", username: "mohanavarma", status: 'active', address: "Latha Nivas, Thiruvannur Nada (PO)", password: "Password@1", password_confirmation: "Password@1", trust: tpkws)


