# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

SuperAdmin.create(name: 'Krishnaprasad Varma', unicode_name: "കൃഷ്ണപ്രസാദ് വർമ്മ", email: "kpvarma@yopmail.com", username: "kpvarma", password: "Password@1", password_confirmation: "Password@1")
SuperAdmin.create(name: 'K C Murali', unicode_name: "കെ സി മുരളി", email: "kcmurali@yopmail.com", username: "kcmurali", password: "Password@1", password_confirmation: "Password@1")
SuperAdmin.create(name: 'Harikrishna Varma', unicode_name: "ഹരികൃഷ്ണ വർമമ", email: "harikrishnan@yopmail.com", username: "hkvarma", password: "Password@1", password_confirmation: "Password@1")

tr_gd =     Trust.create(name: 'Guruvayoor Devaswam',             unicode_name: "ഗുരുവായൂർ ദേവസ്വം", status: 'active', email: "guruvayoor@yopmail.com", phone: "0495-2332332", address: "Administration Block, Guruvayoor Temple, Guruvayoor, Thrissur, Kerala", description: "Guruvayur Sri Krishna Temple (Malayalam: ഗുരുവായൂര്‍ ക്ഷേത്രം, குருவாயூர் கோயில் , ಗುರುವಾಯೂರು ದೇವಸ್ಥಾನ ) is a Hindu temple dedicated to the god Krishna (an avatar of the god Vishnu), located in the town of Guruvayur in Kerala, India. It is one of the most important places of worship for Hindus of Kerala and is often referred to as \"Bhuloka Vaikunta\"[2] which translates to the \"Holy Abode of Vishnu on Earth\". However, even though the shrine is considered to be one of the holiest spots for Vaishnavites (Vishnu followers), the temple is not a part of the famous 108 Divya Desams temple list.")
tr_tst =    Trust.create(name: 'Thiruvannur Shiva Temple Trust',  unicode_name: "തിരുവണ്ണൂർ ശിവ ക്ഷേത്രം Trust", status: 'active', email: "thiruvannur@yopmail.com", phone: "0495-2332332", address: "Shiva Temple, Thiruvannur Nada(PO), Kozhikode, Kerala", description: "This ancient and beautiful Siva temple has an apsidal garbhagriha, decorated with typical Chola pillars and pilasters, panjaras and vyalimukhas. The central shrine has escaped any repair or change and is relatively well preserved. An inscription unearthed records a land grant given to Tirumannur Patarakar in the eighth regnal year of Raja Raja Chera. The record has been dated to 1044 A.D. The deity appears to have been a Jain Tirthankara (since the rules of Thirukkunavaye, the premier Jain shrine of Kerala in Kodungalloor, are cited in the punitive clauses). The Jain temple must have been converted into a Siva temples sometime in the 11th century before the arrival of the Zamorins. The apsidal shrine and other features are attributable to this period.")
tr_tpkws =  Trust.create(name: 'Thiruvannur Puthiya Kovilakam Welfare Society', unicode_name: "തിരുവണ്ണൂർ പുതിയ കോവിലകം വെൽഫെയർ സൊസൈറ്റി", status: 'active', email: "tpkws@yopmail.com", phone: "0495-2341231", address: "Puthiya Kovilakam Welfare Society, Thiruvannur Nada(PO), Kozhikode, Kerala", description: "Zamorin is the anglicised version of Samoothirippadu or Samoothiri Raja, a title of the rulers of the erstwhile Hindu state of Kozhikode (previously known as Calicut), located in the present day state of Kerala, India, between the 14th and 18th century. The royal family is divided into three branches ,viz. Kizhakke (East) Kovilakam, located in Kottakkal, Puthiya (New) Kovilakam, located in Thiruvannur and Padinjara (West) Kovilakam located in Mankaavu, all three are currently within the modern district of Calicut or Kozhikode. The family follows the well-known Marumakkathayam law of inheritance, by which the succession is always to the offspring of its female members only, and among these the next eldest male to the Zamorin is the heir-apparent. On the death of the Zamorin, his successor is always the oldest male from any of these three Kovilakams or branches. The next in line is known as the‘Eralppad Raja’")
tr_sk =     Trust.create(name: 'Thiruvannur Subrahmanya Swamy Kovil Trust',     unicode_name: "തിരുവണ്ണൂർ സുബ്രഹ്മണ്ണ്യ കോവിൽ Trust", status: 'active', email: "kovil@yopmail.com", phone: "0495-2312313", address: "Subrahmannya Kovil, Thiruvannur Nada(PO), Kozhikode, Kerala", description: "")
tr_md =     Trust.create(name: 'Mammiyoor Devaswom',              unicode_name: "മമ്മിയൂർ ദേവസ്വം", status: 'active', email: "mammiyoor@yopmail.com", phone: "0495-2421632", address: "Administrator, Mammiyoor Temple, Guruvayoor, Thrissur, Kerala", description: "Mammiyoor temple or famously known as Mammiyur Mahadeva Kshetram is a Shiva temple situated in Guruvayoor, Thrissur district of Kerala, India.[1] Every devotee who goes to Guruvayur Temple is supposed to go to Mammiyoor also, as the ritual goes. Only Hindus are allowed inside the temple premises. The temple is a part of the 108 famous Shiva temples in Kerala and one among the five Shiva temples around Guruvayoor. The main deity is Shiva and he is facing east and is in rowdra bhava.")
tr_td =     Trust.create(name: 'Tali Devaswom',                   unicode_name: "തളി ദേവസ്വം", status: 'active', email: "tali@yopmail.com", phone: "0495-2428231", address: "Administrator, Tali Devaswam, Tali, Kozhikode, Kerala", description: "A nice temple at Calicut of Lord Shiva. It is a calm temple to visit and well kept.The sanctum is of Lord Shiva while there are other shrines of Lord Krishna, Ganapathi and Devi.")

TrustAdmin.create(name: 'Pritviraj', unicode_name: "പ്രിത്വിരാജ്", email: "rajettan@yopmail.com", username: "rajettan", status: 'active', address: "Puthiya Kovilakam, Thiruvannur Nada (PO)", password: "Password@1", password_confirmation: "Password@1", trust: tr_tst)
TrustAdmin.create(name: 'Jithesh Raja', unicode_name: "ജിതേഷ് രാജാ പി കെ", email: "jitheshettan@yopmail.com", username: "jitheshettan", address: "Jithesh Nivas, Thiruvannur Nada (PO)", status: 'active', password: "Password@1", password_confirmation: "Password@1", trust: tr_tst)
TrustAdmin.create(name: 'Sasi Kumar Raja', unicode_name: "ശശികുമാർ രാജാ പി കെ", email: "sasi@yopmail.com", username: "mohanavarma", status: 'active', address: "Padinjare Kettu, Thiruvannur Nada (PO)", password: "Password@1", password_confirmation: "Password@1", trust: tr_tpkws)
TrustAdmin.create(name: 'Chairman, Guruvayoor Devaswam', unicode_name: "", email: "chairman.gd@yopmail.com", username: "mohanavarma", status: 'active', address: "Latha Nivas, Thiruvannur Nada (PO)", password: "Password@1", password_confirmation: "Password@1", trust: tr_tpkws)

tm_gt = Temple.create(name: 'Guruvayoor temple', unicode_name: "ഗുരുവായൂർ ക്ഷേത്രം", trust: tr_gd, description: "Shiva Temple, Thiruvannur Nada(PO), Kozhikode, Kerala", description: "This ancient and beautiful Siva temple has an apsidal garbhagriha, decorated with typical Chola pillars and pilasters, panjaras and vyalimukhas. The central shrine has escaped any repair or change and is relatively well preserved. An inscription unearthed records a land grant given to Tirumannur Patarakar in the eighth regnal year of Raja Raja Chera. The record has been dated to 1044 A.D. The deity appears to have been a Jain Tirthankara (since the rules of Thirukkunavaye, the premier Jain shrine of Kerala in Kodungalloor, are cited in the punitive clauses). The Jain temple must have been converted into a Siva temples sometime in the 11th century before the arrival of the Zamorins. The apsidal shrine and other features are attributable to this period.")
tm_st = Temple.create(name: 'Shiva temple', unicode_name: "തിരുവണ്ണൂർ ശിവ ക്ഷേത്രം", trust: tr_tst, description: "Shiva Temple, Thiruvannur Nada(PO), Kozhikode, Kerala", description: "This ancient and beautiful Siva temple has an apsidal garbhagriha, decorated with typical Chola pillars and pilasters, panjaras and vyalimukhas. The central shrine has escaped any repair or change and is relatively well preserved. An inscription unearthed records a land grant given to Tirumannur Patarakar in the eighth regnal year of Raja Raja Chera. The record has been dated to 1044 A.D. The deity appears to have been a Jain Tirthankara (since the rules of Thirukkunavaye, the premier Jain shrine of Kerala in Kodungalloor, are cited in the punitive clauses). The Jain temple must have been converted into a Siva temples sometime in the 11th century before the arrival of the Zamorins. The apsidal shrine and other features are attributable to this period.")
tm_bk = Temple.create(name: 'Bhagavathi Kavu', unicode_name: "തിരുവണ്ണൂർ ഭഗവതി കാവ്", trust: tr_tpkws, description: "")
tm_sk = Temple.create(name: 'Thiruvannur Subrahmanya Swamy Kovil', unicode_name: "തിരുവണ്ണൂർ സുബ്രഹ്മണ്ണ്യ കോവിൽ", trust: tr_sk, description: "")

tm_gt_guruvayoorappan = Deity.create(name: 'Guruvayoorappan', unicode_name: "ഗുരുവായൂരപ്പൻ", temple: tm_gt, trust: tr_gd, description: "")
tm_gt_bhagavathi      = Deity.create(name: 'Bhagavathi', unicode_name: "ഭഗവതി", temple: tm_gt, trust: tr_gd, description: "")
tm_gt_shasthavu       = Deity.create(name: 'Shasthavu', unicode_name: "ശാസ്താവ്", temple: tm_gt, trust: tr_gd, description: "")

tm_st_shivan          = Deity.create(name: 'Shivan', unicode_name: "ശിവൻ", temple: tm_st, trust: tr_tst, description: "")
tm_st_krishnan        = Deity.create(name: 'Krishnan', unicode_name: "കൃഷ്ണൻ", temple: tm_st, trust: tr_tst, description: "")
tm_st_ganapathy       = Deity.create(name: 'Ganapathy', unicode_name: "ഗണപതി", temple: tm_st, trust: tr_tst, description: "")
tm_st_dakshinamurthy  = Deity.create(name: 'Dakshinamurthy', unicode_name: "ദക്ഷിണാമൂർത്തി", temple: tm_st, trust: tr_tst, description: "")
tm_st_shasthavu       = Deity.create(name: 'Shasthavu', unicode_name: "ശാസ്താവ്", temple: tm_st, trust: tr_tst, description: "")
tm_st_nagangal        = Deity.create(name: 'Nagangal', unicode_name: "നാഗങ്ങൾ", temple: tm_st, trust: tr_tst, description: "")

tm_bk_shasthavu       = Deity.create(name: 'Shasthavu', unicode_name: "ശാസ്താവ്", temple: tm_bk, trust: tr_tpkws, description: "")
tm_bk_bhagavathy      = Deity.create(name: 'Nagangal', unicode_name: "ഭഗവതി", temple: tm_bk, trust: tr_tpkws, description: "")
tm_bk_nagangal        = Deity.create(name: 'Nagangal', unicode_name: "നാഗങ്ങൾ", temple: tm_bk, trust: tr_tpkws, description: "")

# ----------------------------
# Guruvayoor Temple Offerings
# ----------------------------

# Guruvayoorappan
Offering.create(name: "Pal Payasam",                        unicode_name: "പാല്പായസം",           price: 20.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Nei Payasam",                        unicode_name: "നെയ്പ്പായസം",        price: 20.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Sharkara Payasam",                   unicode_name: "ശര്കരപ്പയാസം",        price: 20.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Paladapradhaman",                    unicode_name: "പാലട പ്രദമൻ",          price: 100.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Irattipayasam",                      unicode_name: "ഇരട്ടി പായസം",         price: 110.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")

Offering.create(name: "Rice Nivedyam",                      unicode_name: "അരി നിവേദ്യം",        price: 10.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Annaprasadam",                       unicode_name: "അന്നപ്രസാദം",         price: 10.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Appam",                              unicode_name: "അപ്പം",                 price: 12.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "Receipts for the Appam vazhipadu will be given from 4 am to 11am, everyday. The prasadam (Appam) will be available after athazhapooja, in the night,till the sheeveli, and on the next day from  5am to 11am.")
Offering.create(name: "Ada",                                unicode_name: "അട",                    price: 10.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "Receipts for the Ada vazhipadu will be given from 4 am to 11am, everyday. The prasadam (Ada) will be available after athazhapooja, in the night,till the sheeveli, and on the next day from  5am to 11am.")
Offering.create(name: "Avil",                               unicode_name: "അവിൽ",                 price: 10.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "Receipts for the Avil vazhipadu will be given from 4 am to 11am, everyday. The prasadam (Avil) will be available after athazhapooja, in the night,till the sheeveli, and on the next day from  5am to 11am.")
Offering.create(name: "Tri-maduram",                        unicode_name: "ത്രിമധുരം",             price: 10.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Butter Nivedyam",                    unicode_name: "വെണ്ണ നിവേദ്യം",    price: 5.00,          devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Sugar & Banana",                     unicode_name: "പഴവും പഞ്ചസാരയും",   price: 10.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Butter After japam",                 unicode_name: "ജപിച്ച വെണ്ണ",      price: 5.00,          devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")

Offering.create(name: "Undamala",                           unicode_name: "ഉണ്ട മാല",             price: 40.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Thirumudimala",                      unicode_name: "തിരുമുടി മാല",        price: 12.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Niramala",                           unicode_name: "നിറമാല",               price: 100.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")

Offering.create(name: "Kelikkayyu",                         unicode_name: "കേളിക്കയ്",           price: 10.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Archana",                            unicode_name: "അർച്ചന",               price: 20.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Purushasooktham",                    unicode_name: "പുരുഷസൂക്തം",         price: 3.00,          devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Archana Ashtotharam",                unicode_name: "അർച്ചന അഷ്ടോത്തരം", price: 4.00,          devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Archana Sahasranamam",               unicode_name: "അർച്ചന സഹസ്രനാമം",  price: 5.00,          devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Alankaram with Kalabham",            unicode_name: "കളഭാലങ്കാരം",          price: 5400.00,       devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Kalabham (1 Ball)",                  unicode_name: "കളഭം (1 ഉണ്ട)",         price: 900.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Kalabham (1 Packet)",                unicode_name: "കളഭം (1 Packet)",        price: 25.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Ghee Lamp",                          unicode_name: "നെയ്‌ വിളക്ക്",        price: 1.00,          devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Small Ghee Lamp (Sreekovil)",        unicode_name: "ചെറിയ നെയ്‌ വിളക്ക് (ശ്രീകോവിൽ )",       price: 500.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Medium Ghee Lamp (Sreekovil)",       unicode_name: "ഇടത്തരം നെയ്‌ വിളക്ക് (ശ്രീകോവിൽ )",      price: 3000.00,       devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Large Ghee Lamp (Sreekovil)",        unicode_name: "വലിയ നെയ്‌ വിളക്ക് (ശ്രീകോവിൽ )",         price: 4500.00,       devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "ThaliPooja",                         unicode_name: "താലിപൂജ",                                      price: 10.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Oil Abishekam (1/4 Ltrs.)",          unicode_name: "എണ്ണ അഭിഷേകം (കാൽ ലിറ്റർ)",              price: 38.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Malar Nivedyam (1/4 Ltrs.)",         unicode_name: "മലർ അഭിഷേകം (കാൽ ലിറ്റർ)",                  price: 4.00,          devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Marriage",                           unicode_name: "വിവാഹം",                                       price: 250.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Ashtapathi (One Chapter)",           unicode_name: "അഷ്ടപതി (1 അധ്യായം) ",                      price: 2.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Bhagavad Geetha (One Chapter)",      unicode_name: "ഭഗവത് ഗീത (1 അധ്യായം) ",       price: 2.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Bagavatham (One Chapter)",           unicode_name: "ഭാഗവതം (1 അധ്യായം) ",           price: 2.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Bagavatha Sapthaham",                unicode_name: "ഭാഗവത സപ്താഹം",                 price: 1000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Narayaneeyam (One deshaka)",         unicode_name: "നാരായണീയം (1 ദശകം)",            price: 2.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Ganapathi Archana",                  unicode_name: "ഗണപതി അരചന",                    price: 3.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Sastha Archana",                     unicode_name: "ശാസ്താ അരചന",                  price: 3.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Lalitha Sahasranamam",               unicode_name: "ലളിതാസഹശ്രനാമം",               price: 5.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Namaskaram",                         unicode_name: "നമസ്കാരം",                        price: 7000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
#Offering.create(name: "Athasham",                          unicode_name: "",                                  price: 7500.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Udayasthamana Pooja",                unicode_name: "ഉദയാസ്തമന പൂജ",                 price: 25000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Ahassu",                             unicode_name: "അഹസ്സ്",                        price: 1500.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Alroopam",                           unicode_name: "ആൾരൂപം",                          price: nil,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Sapthashudhi Abhishekam",            unicode_name: "സപ്തശുധി അഭിഷേകം",            price: 202.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Sapthashudhi Abhishekam (Min)",      unicode_name: "സപ്തശുധി അഭിഷേകം (ചെറുത്)", price: 2.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Gayathri Naijapam",                  unicode_name: "ഗായത്രി നെയ്‌ ജപം",              price: 500.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Illumination",                       unicode_name: "",                                  price: 30000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Krishnanattam Kali",                 unicode_name: "കൃഷ്ണനാട്ടം കളി",               price: 2000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "")
Offering.create(name: "Thulabharam (Thattilpanam)",         unicode_name: "തുലാഭാരം (തട്ടിൽപ്പണം)",        price: 5.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_guruvayoorappan,       notes: "There is no need for taking tickets in advance for the thulabharam vazhipadu.")

# Bhagavathi
Offering.create(name: "Bhagavathi Azhal",                   unicode_name: "ഭഗവതി അഴൽ",           price: 15.00,         devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_bhagavathi,       notes: "")
Offering.create(name: "Illumination Bhagavathi",            unicode_name: "",                       price: 2500.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_bhagavathi,       notes: "")

# Shasthavu
Offering.create(name: "Malayidal (Sabarimala)",             unicode_name: "മാലയിടൽ (ശബരിമല)",              price: 2.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_shasthavu,       notes: "")
Offering.create(name: "Kettunira (sabarimala)",             unicode_name: "കെട്ടുനിറ (ശബരിമല)",            price: 5.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: tm_gt_shasthavu,       notes: "")

# General
Offering.create(name: "Anayoottu",                          unicode_name: "ആനയൂട്ട്‌",                        price: 10000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Gopooja",                            unicode_name: "ഗോപൂജ",                           price: 250.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Gopreethi",                          unicode_name: "ഗൊപ്രീതി",                       price: 10.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Maintenance of Elephants",           unicode_name: "",                                  price: nil,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")

Offering.create(name: "Chuttambalam Theliyikkal",           unicode_name: "ചുറ്റംബലം തെളിയിക്കൽ",         price: 10000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Palakappuram Theliyikkal",           unicode_name: "പലകപ്പുറം തെളിയിക്കൽ",         price: 3000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Deepastambam Theliyikkal",           unicode_name: "ദീപസ്തംഭം തെളിയിക്കൽ",         price: 3000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Chuttu Vilakku",                     unicode_name: "ചുറ്റുവിലക്കു",                  price: 3000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Veda Parayanam",                     unicode_name: "വേദപാരായണം",                     price: 1000.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")

Offering.create(name: "Vahana Pooja (Bus,Lorry etc.)",      unicode_name: "വാഹന പൂജ (Bus,Lorry etc.)",      price: 300.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Vahana Pooja (Car,Jeep etc.)",       unicode_name: "വാഹന പൂജ (Car,Jeep etc.)",       price: 150.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Vahana Pooja (Auto, Bike etc.)",     unicode_name: "വാഹന പൂജ (Auto, Bike etc.)",     price: 75.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Vidyarambham",                       unicode_name: "വിദ്യാരംഭം",                       price: 5.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")
Offering.create(name: "Choroonu",                           unicode_name: "ചോറൂണ്‍",                         price: 5.00,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "The choroonu for kids will not be conducted on Ekadasi and Vavu Night. The choroonu will not be conducted on Guruvayur Ekadasi Day.")

Offering.create(name: "Prasadaoottu",                       unicode_name: "പ്രസാദ ഊട്ട്",                    price: nil,        devaswam_share: nil,        shanti_share: nil,        kazhakam_share: nil,      temple: tm_gt,       deity: nil,       notes: "")


# Thiruvannur Shiva Temple Offerings
# ----------------------------------

bkv_pushpanjali         = Offering.create(name: 'Pushpanjali', unicode_name: "", price: 10.0, temple: tm_bk, deity: tm_bk_bhagavathy, notes: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
bkv_raktha_pushpanjali  = Offering.create(name: 'Raktha Pushpanjali', unicode_name: "", price: 20.0, temple: tm_bk, deity: tm_bk_bhagavathy, notes: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
bkv_bg_pushpanjali      = Offering.create(name: 'Bagyasooktha Pushpanjali', unicode_name: "", price: 25.0, temple: tm_bk, deity: tm_bk_bhagavathy, notes: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
bkv_sv_pushpanjali      = Offering.create(name: 'Swayamvara Pushpanjali', unicode_name: "", price: 30.0, temple: tm_bk, deity: tm_bk_bhagavathy, notes: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
bkv_neyvilakku_small    = Offering.create(name: 'Neyvilakku (small)', unicode_name: "", price: 20.0, temple: tm_bk, deity: tm_bk_bhagavathy, notes: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
bkv_neyvilakku_large    = Offering.create(name: 'Neyvilakku (large)', unicode_name: "", price: 30.0, temple: tm_bk, deity: tm_bk_bhagavathy, notes: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
bkv_thiru_madhuram      = Offering.create(name: 'Thiru Madhuram', unicode_name: "", price: 30.0, temple: tm_bk, deity: tm_bk_bhagavathy, notes: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
bkv_thiru_madhuram      = Offering.create(name: 'Thiru Madhuram', unicode_name: "", price: 30.0, temple: tm_bk, deity: tm_bk_bhagavathy, notes: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")



